FROM node:10

# Create app directory
WORKDIR /usr/src/app

RUN npm i -g @nestjs/cli

RUN git clone https://github.com/labarca/nest-started.git

WORKDIR /usr/src/app/nest-started

RUN npm install


EXPOSE 3000

CMD ["npm", "run", "start"]